(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<< "C:\\Documents and Settings\\ocroissant\\My Documents\\NumericalIntegration.m"


<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BS.m"


Needs["PlotLegends`"]


SuperBiHestonLaplaceTransform[M_,Q_,{{\[Theta]11_,\[Theta]12_},{\[Theta]12_,\[Theta]22_}},\[Rho]_,\[Mu]_,{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]12_,\[CapitalSigma]22_}},\[Gamma]_,\[Beta]_,\[Tau]_]:=
Module[{H,EXPH,A11,A21,A,\[Nu]11,\[Nu]12,\[Nu]21,\[Nu]22,c,\[CapitalSigma]=({
 {\[CapitalSigma]11, \[CapitalSigma]12},
 {\[CapitalSigma]12, \[CapitalSigma]22}
}),\[CapitalSigma]infM=({
 {\[Theta]11, \[Theta]12},
 {\[Theta]12, \[Theta]22}
}),M\[Mu]=DiagonalMatrix[\[Mu]],
Placement1={{1,0,0,0},{0,1,0,0}},Placement2={{0,0,1,0},{0,0,0,1}}},
H=Transpose[Placement1] .(-( M+Transpose[Q].Outer[Times,\[Rho],\[Gamma]])/2).Placement1+
Transpose[Placement1] .(-Transpose[Q]. Q/2).Placement2+
Transpose[Placement2] . (1/2 Outer[Times,\[Gamma],\[Gamma]]+DiagonalMatrix[M\[Mu].\[Gamma]-\[Gamma]/2] ).Placement1+
Transpose[Placement2] . (Transpose[(M+Transpose[Q].Outer[Times,\[Rho],\[Gamma]])/2]).Placement2 ; 
EXPH=MatrixExp[\[Tau] H];
A11={{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}};
A21={{EXPH[[3,1]],EXPH[[3,2]]},{EXPH[[4,1]],EXPH[[4,2]]}};
A=Inverse[A11] .A21;
c=-2\[Beta]^2 (Tr[MatrixLog2[A11]+\[Tau]/2 (Transpose[M]+Outer[Times,\[Gamma],\[Rho]].Q)]); (*c=-(\[Beta]/2) Tr[Log[A22]+\[Tau] (Transpose[M]+Outer[Times,\[Gamma],\[Rho]].Q)];*)
Exp[Tr[A . \[CapitalSigma]]+c]
]


SuperBiHestonLaplaceTransform[M_,Q_,{{\[Theta]11_,\[Theta]12_},{\[Theta]12_,\[Theta]22_}},\[Rho]_,\[Mu]_,{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]12_,\[CapitalSigma]22_}},\[Gamma]_,\[Beta]_,\[Tau]_]:=
Module[{H,EXPH,A11,A21,A,\[Nu]11,\[Nu]12,\[Nu]21,\[Nu]22,c,\[CapitalSigma]=({
 {\[CapitalSigma]11, \[CapitalSigma]12},
 {\[CapitalSigma]12, \[CapitalSigma]22}
}),\[CapitalSigma]infM=({
 {\[Theta]11, \[Theta]12},
 {\[Theta]12, \[Theta]22}
}),M\[Mu]=DiagonalMatrix[\[Mu]],
Placement1={{1,0,0,0},{0,1,0,0}},Placement2={{0,0,1,0},{0,0,0,1}}},
H=Transpose[Placement1] .(-( M+Transpose[Q].Outer[Times,\[Rho],\[Gamma]])/2).Placement1+
Transpose[Placement1] .(-Transpose[Q]. Q/2).Placement2+
Transpose[Placement2] . (1/2 Outer[Times,\[Gamma],\[Gamma]]+DiagonalMatrix[M\[Mu].\[Gamma]-\[Gamma]/2] ).Placement1+
Transpose[Placement2] . (Transpose[(M+Transpose[Q].Outer[Times,\[Rho],\[Gamma]])/2]).Placement2 ; 
EXPH=MatrixExp[\[Tau] H];
A11={{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}};
A21={{EXPH[[3,1]],EXPH[[3,2]]},{EXPH[[4,1]],EXPH[[4,2]]}};
A=Inverse[A11] .A21;
c=-2\[Beta]^2 (Tr[MatrixLog2[A11]+\[Tau]/2 (Transpose[M]+Outer[Times,\[Gamma],\[Rho]].Q)]); (*c=-(\[Beta]/2) Tr[Log[A22]+\[Tau] (Transpose[M]+Outer[Times,\[Gamma],\[Rho]].Q)];*)
Exp[Tr[A . \[CapitalSigma]]+c]
]


BiHestonLaplaceQuickTransform[{{M11_,M12_},{M21_,M22_}},{{Q11_,Q12_},{Q21_,Q22_}},{\[Rho]1_,\[Rho]2_},{\[Mu]1_,\[Mu]2_},{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]21_,\[CapitalSigma]22_}},{\[Gamma]1_,\[Gamma]2_},\[Beta]_,\[Tau]_]:=
Module[{EXPH,X11=Q11 \[Rho]1+Q21 \[Rho]2,X12=Q12  \[Rho]1+Q22  \[Rho]2,\[Delta]},
EXPH=MatrixExp[\[Tau] {{1/2 (-M11-X11 \[Gamma]1 ),1/2 (-M12-X11 \[Gamma]2 ),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-X12 \[Gamma]1 ),1/2 (-M22-X12 \[Gamma]2 ),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{-(\[Gamma]1/2)+\[Gamma]1^2/2+\[Gamma]1 \[Mu]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+X11 \[Gamma]1 ),1/2 (M21+X12 \[Gamma]1)},{(\[Gamma]1 \[Gamma]2)/2,-(\[Gamma]2/2)+\[Gamma]2^2/2+\[Gamma]2 \[Mu]2,1/2 (M12+X11 \[Gamma]2 ),1/2 (M22+X12 \[Gamma]2 )}}];
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2\[Beta]^2 (Log[\[Delta]]+\[Tau]/2 ( M11+M22+Q11 \[Gamma]1 \[Rho]1+Q12 \[Gamma]2 \[Rho]1+Q21 \[Gamma]1 \[Rho]2+Q22 \[Gamma]2 \[Rho]2))]
]


BiHestonLaplaceQuickTransformReverse[{{M22_,M21_},{M12_,M11_}},{{Q22_,Q21_},{Q12_,Q11_}},{\[Rho]2_,\[Rho]1_},{\[Mu]2_,\[Mu]1_},{{\[CapitalSigma]22_,\[CapitalSigma]21_},{\[CapitalSigma]12_,\[CapitalSigma]11_}},{\[Gamma]1_,\[Gamma]2_},\[Beta]_,\[Tau]_]:=
Module[{EXPH,X11=Q11 \[Rho]1+Q21 \[Rho]2,X12=Q12  \[Rho]1+Q22  \[Rho]2,\[Delta]},
EXPH=MatrixExp[\[Tau] {{1/2 (-M11-X11 \[Gamma]1 ),1/2 (-M12-X11 \[Gamma]2 ),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-X12 \[Gamma]1 ),1/2 (-M22-X12 \[Gamma]2 ),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{-(\[Gamma]1/2)+\[Gamma]1^2/2+\[Gamma]1 \[Mu]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+X11 \[Gamma]1 ),1/2 (M21+X12 \[Gamma]1)},{(\[Gamma]1 \[Gamma]2)/2,-(\[Gamma]2/2)+\[Gamma]2^2/2+\[Gamma]2 \[Mu]2,1/2 (M12+X11 \[Gamma]2 ),1/2 (M22+X12 \[Gamma]2 )}}];
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2\[Beta]^2 (Log[\[Delta]]+\[Tau]/2 ( M11+M22+Q11 \[Gamma]1 \[Rho]1+Q12 \[Gamma]2 \[Rho]1+Q21 \[Gamma]1 \[Rho]2+Q22 \[Gamma]2 \[Rho]2))]
]


BiHestonLaplaceQuickTransform2[{{M11_,M12_},{M21_,M22_}},{{Q11_,Q12_},{Q21_,Q22_}},{\[Rho]1_,\[Rho]2_},{\[Mu]1_,\[Mu]2_},{{\[CapitalSigma]11_,\[CapitalSigma]12_},{\[CapitalSigma]21_,\[CapitalSigma]22_}},{\[Gamma]1_,\[Gamma]2_},{{\[Beta]11_,\[Beta]12_},{\[Beta]21_,\[Beta]22_}},\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{-(\[Gamma]1/2)+\[Gamma]1^2/2+\[Gamma]1 \[Mu]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,-(\[Gamma]2/2)+\[Gamma]2^2/2+\[Gamma]2 \[Mu]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta],LogA11},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
LogA11=MatrixLog2[{{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}}];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2(\[Beta]11 LogA11[[1,1]]+\[Beta]12 LogA11[[1,2]]+\[Beta]21 LogA11[[2,1]]+\[Beta]22 LogA11[[2,2]]+1/2 (\[Beta]11 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2)+\[Beta]21 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)+\[Beta]12 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2)+\[Beta]22 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)) \[Tau])]
]


BiHestonLaplaceQuickTransformReverse2[{{M22_,M21_},{M12_,M11_}},{{Q22_,Q21_},{Q12_,Q11_}},{\[Rho]2_,\[Rho]1_},{\[Mu]2_,\[Mu]1_},{{\[CapitalSigma]22_,\[CapitalSigma]21_},{\[CapitalSigma]12_,\[CapitalSigma]11_}},{\[Gamma]1_,\[Gamma]2_},{{\[Beta]11_,\[Beta]12_},{\[Beta]21_,\[Beta]22_}},\[Tau]_]:=
Module[{EXPH=MatrixExp[\[Tau] {{1/2 (-M11-Q11 \[Gamma]1 \[Rho]1-Q21 \[Gamma]1 \[Rho]2),1/2 (-M12-Q11 \[Gamma]2 \[Rho]1-Q21 \[Gamma]2 \[Rho]2),1/2 (-Q11^2-Q21^2),1/2 (-Q11 Q12-Q21 Q22)},{1/2 (-M21-Q12 \[Gamma]1 \[Rho]1-Q22 \[Gamma]1 \[Rho]2),1/2 (-M22-Q12 \[Gamma]2 \[Rho]1-Q22 \[Gamma]2 \[Rho]2),1/2 (-Q11 Q12-Q21 Q22),1/2 (-Q12^2-Q22^2)},{-(\[Gamma]1/2)+\[Gamma]1^2/2+\[Gamma]1 \[Mu]1,(\[Gamma]1 \[Gamma]2)/2,1/2 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2),1/2 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)},{(\[Gamma]1 \[Gamma]2)/2,-(\[Gamma]2/2)+\[Gamma]2^2/2+\[Gamma]2 \[Mu]2,1/2 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2),1/2 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)}}],\[Delta],LogA11},
\[Delta]=-EXPH[[1,2]] EXPH[[2,1]]+EXPH[[1,1]] EXPH[[2,2]];
LogA11=MatrixLog2[{{EXPH[[1,1]],EXPH[[1,2]]},{EXPH[[2,1]],EXPH[[2,2]]}}];
Exp[1/\[Delta] (EXPH[[2,2]] EXPH[[3,1]] \[CapitalSigma]11-EXPH[[1,2]] EXPH[[4,1]] \[CapitalSigma]11-EXPH[[2,1]] EXPH[[3,1]] \[CapitalSigma]12+EXPH[[2,2]] EXPH[[3,2]] \[CapitalSigma]12+
EXPH[[1,1]] EXPH[[4,1]] \[CapitalSigma]12-EXPH[[1,2]] EXPH[[4,2]] \[CapitalSigma]12-EXPH[[2,1]] EXPH[[3,2]] \[CapitalSigma]22+EXPH[[1,1]] EXPH[[4,2]] \[CapitalSigma]22)-2(\[Beta]11 LogA11[[1,1]]+\[Beta]12 LogA11[[1,2]]+\[Beta]21 LogA11[[2,1]]+\[Beta]22 LogA11[[2,2]]+1/2 (\[Beta]11 (M11+Q11 \[Gamma]1 \[Rho]1+Q21 \[Gamma]1 \[Rho]2)+\[Beta]21 (M21+Q12 \[Gamma]1 \[Rho]1+Q22 \[Gamma]1 \[Rho]2)+\[Beta]12 (M12+Q11 \[Gamma]2 \[Rho]1+Q21 \[Gamma]2 \[Rho]2)+\[Beta]22 (M22+Q12 \[Gamma]2 \[Rho]1+Q22 \[Gamma]2 \[Rho]2)) \[Tau])]
]


MatrixExp2[{{a_,b_},{c_,d_}}]:=Module[{det=Sqrt[a^2+4 b c-2 a d+d^2],expdet,expab},expdet=\[ExponentialE]^det;expab=\[ExponentialE]^(1/2 (a+d-det));{{(expab (d-d expdet+a (-1+expdet)+det (1+expdet)))/(2 det),(b expab (-1+expdet))/det},{(c expab (-1+expdet))/det,(expab (a-a expdet+d (-1+expdet)+det (1+expdet)))/(2 det)}}]


MatrixLog2[{{a_,b_},{c_,d_}}]:=Module[{logdetm,adm,adp,logdetp,log4,P,InvP,det=Sqrt[a^2+4 b c-2 a d+d^2]},
If[det==0, det= 10^(-30)];
adm=a+d-det;adp=a+d+det;
If[Re[adm]==0,adm+=10^(-30)];
If[Re[adp]==0,adp+=10^(-30)];
If[(Im[adm]==0)&&(Re[adm]<=0),logdetm=0,logdetm=Log[adm]];
If[(Im[adp]==0)&&(Re[adp]<=0),logdetp=0,logdetp=Log[adp]];
log4=Log[4];{{(-det log4+(-a+d+det) logdetm+(a-d+det) logdetp)/(2 det),(-b (logdetm-logdetp))/ det},{(c (-logdetm+logdetp))/det,(-det log4+(a-d+det) logdetm+(-a+d+det)logdetp)/(2 det)}}
]


TrMatrixLog2[{{a_,b_},{c_,d_}}]:=Module[{},
Log[- b c+a d]
]


\[Beta]Optimal[\[Nu]1_,\[Chi]1_,\[CapitalSigma]inf1_,\[Nu]2_,\[Chi]2_,\[CapitalSigma]inf2_]:=(2 (\[Chi]1 \[Nu]2^2 \[CapitalSigma]inf1+\[Chi]2 \[Nu]1^2 \[CapitalSigma]inf2))/(\[Nu]1^2 \[Nu]2^2)


\[Beta]Optimal2[\[Nu]1_,\[Chi]1_,\[CapitalSigma]inf1_,\[Nu]2_,\[Chi]2_,\[CapitalSigma]inf2_]:=(4 (Max[\[Chi]1 \[Nu]2^2 \[CapitalSigma]inf1,\[Chi]2 \[Nu]1^2 \[CapitalSigma]inf2]))/(\[Nu]1^2 \[Nu]2^2)


MDeterminant[\[Nu]1_,\[Chi]1_,\[CapitalSigma]inf1_,\[Nu]2_,\[Chi]2_,\[CapitalSigma]inf2_,\[CapitalSigma]12_,\[Beta]_]:=-\[Beta]^2 \[Nu]1^2 \[Nu]2^2+\[Beta] (4 \[Chi]1  \[Nu]2^2 \[CapitalSigma]inf1+4 \[Chi]2 \[Nu]1^2 \[CapitalSigma]inf2)+16 \[Chi]1 \[Chi]2 (\[CapitalSigma]12^2-\[CapitalSigma]inf1 \[CapitalSigma]inf2)


DetermineQ[\[Rho]1_,\[Rho]2_,\[Nu]1_,\[Nu]2_,\[Rho]s1_,\[Rho]s2_,printflag_]:=Module[{Q11,Q21,Q12,Q22},
If[(\[Rho]1!=0)||(\[Rho]2!=0),
Q11=(\[Nu]1 ( \[Rho]1 \[Rho]s1-\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2- \[Rho]s1^2)]))/(2  (\[Rho]1^2+\[Rho]2^2));Q21=(\[Nu]1 ( \[Rho]2 \[Rho]s1+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2- \[Rho]s1^2)]))/(2 (\[Rho]1^2+\[Rho]2^2));Q12=(\[Nu]2 ( \[Rho]1 \[Rho]s2-\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2- \[Rho]s2^2)]))/(2  (\[Rho]1^2+\[Rho]2^2));Q22=(\[Nu]2 (\[Rho]2 \[Rho]s2+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2- \[Rho]s2^2)]))/(2 (\[Rho]1^2+\[Rho]2^2));
If[((Q11==0)&&(Q12==0))||((Q21==0)&&(Q22==0)),Q11=(\[Nu]1 (\[Rho]1^2 \[Rho]s1-\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q21=(\[Nu]1 (\[Rho]2 \[Rho]s1+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 (\[Rho]1^2+\[Rho]2^2));Q12=(\[Nu]2 (\[Rho]1^2 \[Rho]s2+\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q22=(\[Nu]2 \[Rho]2 \[Rho]s2-\[Nu]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)])/(2 (\[Rho]1^2+\[Rho]2^2))];
If[((Q11==0)&&(Q12==0))||((Q21==0)&&(Q22==0)),Q11=(\[Nu]1 (\[Rho]1^2 \[Rho]s1+\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q21=(\[Nu]1 \[Rho]2 \[Rho]s1-\[Nu]1 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)])/(2 (\[Rho]1^2+\[Rho]2^2));Q12=(\[Nu]2 (\[Rho]1^2 \[Rho]s2-\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q22=(\[Nu]2 (\[Rho]2 \[Rho]s2+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 (\[Rho]1^2+\[Rho]2^2))];
If[((Q11==0)&&(Q12==0))||((Q21==0)&&(Q22==0)),Q11=(\[Nu]1 (\[Rho]1^2 \[Rho]s1+\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q21=(\[Nu]1 \[Rho]2 \[Rho]s1-\[Nu]1 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)])/(2 (\[Rho]1^2+\[Rho]2^2));Q12=(\[Nu]2 (\[Rho]1^2 \[Rho]s2+\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2));Q22=(\[Nu]2 \[Rho]2 \[Rho]s2-\[Nu]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)])/(2 (\[Rho]1^2+\[Rho]2^2))];
,Print["error: \[Rho]1==0 and \[Rho]2==0"]];
If[printflag>0,Print["{\[Rho]1,\[Rho]2,\[Nu]1,\[Nu]2,\[Rho]s1,\[Rho]s2}=",{\[Rho]1,\[Rho]2,\[Nu]1,\[Nu]2,\[Rho]s1,\[Rho]s2}]];
If[printflag>0,Print["Autres sol=",{{(\[Nu]1 (\[Rho]1^2 \[Rho]s1-\[Rho]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 \[Rho]1 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]1 (\[Rho]2 \[Rho]s1+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 (\[Rho]1 \[Rho]s2+\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 \[Rho]2 \[Rho]s2-\[Nu]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)])/(2 (\[Rho]1^2+\[Rho]2^2))},{(\[Nu]1 (\[Rho]1 \[Rho]s1+\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]1 \[Rho]2 \[Rho]s1-\[Nu]1 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)])/(2 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 (\[Rho]1 \[Rho]s2-\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2  (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 (\[Rho]2 \[Rho]s2+Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2 (\[Rho]1^2+\[Rho]2^2))},{(\[Nu]1 (\[Rho]1 \[Rho]s1+\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)]))/(2  (\[Rho]1^2+\[Rho]2^2)),(\[Nu]1 \[Rho]2 \[Rho]s1-\[Nu]1 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s1^2)])/(2 (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 (\[Rho]1 \[Rho]s2+\[Rho]2 Sqrt[ (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)]))/(2  (\[Rho]1^2+\[Rho]2^2)),(\[Nu]2 \[Rho]2 \[Rho]s2-\[Nu]2 Sqrt[\[Rho]1^2 (\[Rho]1^2+\[Rho]2^2-\[Rho]s2^2)])/(2 (\[Rho]1^2+\[Rho]2^2))}}]];
{{Q11,Q12},{Q21,Q22}}]



DetermineM[Q_,\[Beta]_,\[CapitalSigma]inf1_,\[CapitalSigma]inf2_,\[Chi]1_,\[Chi]2_,\[CapitalSigma]012_,flag_]:=Module[{M11=-\[Chi]1/2,M22=-\[Chi]2/2,M21,M12,M,\[Nu]1,\[Nu]2},
\[Nu]1=Sqrt[4(Q[[1,1]]^2+Q[[2,1]]^2)];\[Nu]2=Sqrt[4(Q[[1,2]]^2+Q[[2,2]]^2)];

M21=(\[Beta] (Q[[1,1]]^2+Q[[2,1]]^2)-\[Chi]1 \[CapitalSigma]inf1)/(2\[CapitalSigma]012);
M12=(\[Beta] (Q[[1,2]]^2+Q[[2,2]]^2)-\[Chi]2 \[CapitalSigma]inf2)/(2\[CapitalSigma]012);
M={{M11,M12},{M21,M22}};
If[flag==1,
Print["Q_,\[Beta],\[CapitalSigma]inf1,\[CapitalSigma]inf2,\[Chi]1,\[Chi]2,\[CapitalSigma]012=",{Q,\[Beta],\[CapitalSigma]inf1,\[CapitalSigma]inf2,\[Chi]1,\[Chi]2,\[CapitalSigma]012}];
Print["\!\(\*SuperscriptBox[\"\[Nu]1\", \"2\"]\)/2-\[Chi]1 \[CapitalSigma]inf1 doit etre negatif 1 : ",\[Nu]1^2/2-\[Chi]1 \[CapitalSigma]inf1];
Print["\!\(\*SuperscriptBox[\"\[Nu]2\", \"2\"]\)/2-\[Chi]2 \[CapitalSigma]inf2 doit etre negatif 2 : ",\[Nu]2^2/2-\[Chi]2 \[CapitalSigma]inf2];
Print["eigenvalues[M]=",Eigenvalues[M]];];
M
]


HestonPropagator[V_,\[Tau]_,\[Lambda]_,\[Theta]_,\[Nu]_,\[Rho]_,z_]:=Module[{\[Psi]p,\[Psi]m,\[Zeta],X},
\[Zeta]=Sqrt[( \[Lambda]+I z \[Rho] \[Nu])^2+\[Nu]^2(-I z+z^2)];
\[Psi]p=-(\[Lambda]+I z \[Rho] \[Nu])+\[Zeta];
\[Psi]m=( \[Lambda]+I z \[Rho] \[Nu])+\[Zeta];
A=-\[Theta] \[Lambda]/\[Nu]^2(\[Psi]p \[Tau]+2 Log[(\[Psi]m+\[Psi]p \[ExponentialE]^(-\[Zeta]  \[Tau]))/(2 \[Zeta])]);
B=-(-I z+z^2)(1-\[ExponentialE]^(-\[Zeta]  \[Tau]))/(\[Psi]m+\[Psi]p \[ExponentialE]^(-\[Zeta]  \[Tau]));
\[ExponentialE]^(A+B  V)]


FourierPayOffLNSepp[z_,k_]:=k^(\[ImaginaryI] z+1)/(z^2-\[ImaginaryI] z)


LNHestonVanillaCallIntegrand[F_,K_,z_,V_,\[Tau]_,\[Theta]_,\[Lambda]_,\[Nu]_,\[Rho]_]:=
Module[{\[Psi]p,\[Psi]m,\[Zeta],X},
Re[\[ExponentialE]^(-Log[F] I z) HestonPropagator[V,\[Tau],\[Lambda],\[Theta],\[Nu],\[Rho],z]FourierPayOffLNSepp[z,K]]]


LNHestonVanillaCall[F_,K_,V0_,\[Tau]_,\[Lambda]_,\[Theta]_,\[Nu]_,\[Rho]_,limsup_]:=
F+1/Pi NIntegrate[
LNHestonVanillaCallIntegrand[F,K,k1+I/2,V0,\[Tau],\[Theta],\[Lambda],\[Nu],\[Rho]],{k1,0,limsup},MaxRecursion->20]


LNHestonRiccatiVanillaCallIntegrand[F_,K_,z_,V_,\[Tau]_,\[Theta]_,\[Lambda]_,\[Nu]_,\[Rho]_]:=
Module[{\[Psi]p,\[Psi]m,\[Zeta],X},
Re[\[ExponentialE]^(-Log[F] I z) HestonLaplaceTransform4[-\[Lambda],\[Theta],\[Rho], V,-\[ImaginaryI] z,\[Nu],\[Tau]]FourierPayOffLNSepp[z,K]]]


LNHestonRiccatiVanillaCall[F_,K_,V0_,\[Tau]_,\[Lambda]_,\[Theta]_,\[Nu]_,\[Rho]_,limsup_]:=
F+1/Pi NIntegrate[
LNHestonRiccatiVanillaCallIntegrand[F,K,k1+I/2,V0,\[Tau],\[Theta],\[Lambda],\[Nu],\[Rho]],{k1,0,limsup},MaxRecursion->20]


HestonLaplaceTransform4[M_,\[Theta]_,\[Rho]_, \[CapitalSigma]_,\[Gamma]_,Q_,\[Tau]_]:=
Module[{H,EXPH,A11,A1,A21,A,\[Beta],\[Nu]11,\[Nu]12,\[Nu]21,\[Nu]22,c,
Placement1={{1,0}},Placement2={{0,1}},\[Zeta]},
\[Beta]=Sqrt[-M \[Theta]]/Q;
H=-( (M+Q \[Rho] \[Gamma])/2)( Transpose[Placement1] .Placement1)+
(-Q  Q/2)(Transpose[Placement1] .Placement2)+
(\[Gamma] \[Gamma] /2-\[Gamma]/2)(Transpose[Placement2]  .Placement1)+
((M+Q \[Rho] \[Gamma])/2)(Transpose[Placement2]  .Placement2) ; 
EXPH=MatrixExp2[\[Tau] H];
A11=EXPH[[1,1]];
A21=EXPH[[2,1]];
A= A21/A11;
c=-2\[Beta]^2 (Log[A11]+\[Tau]/2 (M+\[Gamma] \[Rho] Q)); 
Exp[A  \[CapitalSigma]+c]
]


HestonFourierTransform4[M_,\[Theta]_,\[Rho]_, \[CapitalSigma]_,\[Gamma]_,\[Beta]_,\[Tau]_]:=HestonLaplaceTransform4[M,\[Theta],\[Rho], \[CapitalSigma],-\[ImaginaryI] \[Gamma],\[Beta],\[Tau]]


HestonLaplaceTransform[M_,\[Theta]_,\[Rho]_, \[CapitalSigma]_,\[Gamma]_,Q_,\[Tau]_]:=
Module[{H,EXPH,A11,A1,A21,A,\[Nu]11,\[Nu]12,\[Nu]21,\[Nu]22,c,
Placement1={{1,0}},Placement2={{0,1}},\[Zeta],\[Beta]=Sqrt[-M \[Theta]]/Q},
H=-( (M+Q \[Rho] \[Gamma])/2)( Transpose[Placement1] .Placement1)+
(-Q  Q/2)(Transpose[Placement1] .Placement2)+
(\[Gamma] \[Gamma] /2)(Transpose[Placement2]  .Placement1)+
((M+Q \[Rho] \[Gamma])/2)(Transpose[Placement2]  .Placement2) ; 
EXPH=MatrixExp2[\[Tau] H];
A11=EXPH[[1,1]];
A21=EXPH[[2,1]];
A= A21/A11;
c=-2\[Beta]^2 (Log[A11]+\[Tau]/2 (M+\[Gamma] \[Rho] Q)); 
Exp[A  \[CapitalSigma]+c]
]


HestonFourierTransform[M_,\[Theta]_,\[Rho]_, \[CapitalSigma]_,\[Gamma]_,\[Beta]_,\[Tau]_]:=HestonLaplaceTransform[M,\[Theta],\[Rho], \[CapitalSigma],-\[ImaginaryI] \[Gamma],\[Beta],\[Tau]]


GaussianHestonFondamentalTransform[\[Rho]_,M_,\[CapitalSigma]inf_,Q_,V_,\[Gamma]_,\[Tau]_]:=Module[{\[Zeta],\[Psi]p ,\[Psi]m,A,B,arg\[Zeta]},
arg\[Zeta]=(M+\[ImaginaryI] \[Rho] Q \[Gamma])^2+Q^2 ( \[Gamma]^2);
If[Abs[arg\[Zeta]]<=10^(-200),
B=( M+\[ImaginaryI] \[Rho] \[Gamma] Q)/Q^2-(( M-\[ImaginaryI] \[Rho] \[Gamma] Q)Q^2)/ \[Tau] ( M+\[ImaginaryI]  \[Rho] \[Gamma] Q)+Q^4;
A=1/(2 Q^2) (\[CapitalSigma]inf M (2 M \[Tau]+2 \[ImaginaryI] Q \[Rho] \[Tau] \[Gamma]-2 \[ImaginaryI] Q^4 ArcTan[(Q \[Rho] \[Tau] \[Gamma])/(Q^4+M \[Tau])]+Q^4 Log[Q^8/(Q^8+2 Q^4 M \[Tau]+M^2 \[Tau]^2+Q^2 \[Rho]^2 \[Tau]^2 \[Gamma]^2)]));
\[ExponentialE]^(A+B V),
\[Zeta]=Sqrt[(M+\[ImaginaryI] \[Rho] Q \[Gamma])^2+Q^2 ( \[Gamma]^2)];
\[Psi]p =-(M+\[ImaginaryI] \[Rho] Q  \[Gamma])+\[Zeta];
\[Psi]m =(M+\[ImaginaryI] \[Rho] Q  \[Gamma])+\[Zeta];
A=-( \[CapitalSigma]inf M (\[Tau] \[Psi]p+2 Log[(\[Psi]m+\[ExponentialE]^(-\[Zeta] \[Tau]) \[Psi]p)/(2\[Zeta])])/ (Q^2)   );
B= -( \[Gamma]^2)(1-\[ExponentialE]^(-\[Zeta]  \[Tau]))/(\[Psi]m+\[Psi]p \[ExponentialE]^(-\[Zeta]  \[Tau]));
If[Re[A+B V]<-100,0,
\[ExponentialE]^(A+B V)]]]


phi[x_]:=Exp[-x^2/2]/Sqrt[2Pi]


Nd[x_]:=(Erf[x/Sqrt[2]]+1)/2


LogNormalSpreadDigitaleCall[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=NIntegrate[phi[x]Nd[-(Log[(k+S2 E^(-1/2 sig2^2 t+sig2 Sqrt[t] x))/(S1 E^(-1/2 sig1^2 t))]-rho sig1 Sqrt[t] x)/(Sqrt[1-rho^2] sig1 Sqrt[t])],{x,-Infinity,-1,+Infinity}]


MesureQTLogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 ,S2 ,sig1,sig2,rho,k,t]


MesureQ1LogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 Exp[sig1^2 t],S2 Exp[rho sig1 sig2 t],sig1,sig2,rho,k,t]


MesureQ2LogNormalSpreadDigitale[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadDigitaleCall[S1 Exp[rho sig1 sig2 t],S2 Exp[sig2^2 t],sig1,sig2,rho,k,t]


LogNormalSpreadOptionAux[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=S1 MesureQ1LogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]-S2 MesureQ2LogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]-k MesureQTLogNormalSpreadDigitale[S1,S2,sig1,sig2,rho,k,t]


LogNormalSpreadOption[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=LogNormalSpreadOptionAux[S1,S2,sig1,sig2,rho,k,t] /; k>=0


LogNormalSpreadOption[S1_,S2_,sig1_,sig2_,rho_,k_,t_]:=S1-S2-k+LogNormalSpreadOptionAux[S2,S1,sig2,sig1,rho,-k,t] /; k<0



