(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<< "C:\\Documents and Settings\\ocroissant\\My Documents\\NumericalIntegration.m"


<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BS.m"


<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BiHeston\\Heston_Definitif.m"


<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BiHeston\\BiHeston_VanillaInstruments.m"


<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BiHeston\\BiHeston_Calibration.m"


LNHestonFondamentalTransform[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Omega]_,\[Tau]_]:=
Module[{\[Zeta]1,\[Psi]p1 ,\[Psi]m1,B1,arg\[Zeta]1,\[Zeta]2,\[Psi]p2 ,\[Psi]m2,A2,B2,arg\[Zeta]2,A},
arg\[Zeta]1=(\[Lambda]v1+\[Rho]1 \[Kappa]1 I \[Omega])^2+\[Kappa]1^2( \[Omega]^2-I \[Omega]);
\[Zeta]1=Sqrt[arg\[Zeta]1];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I \[Omega])+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I \[Omega])+\[Zeta]1;
B1= -( \[Omega]^2-I \[Omega])(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
arg\[Zeta]2=(\[Lambda]v2+\[Rho]2 \[Kappa]2 I \[Omega])^2+\[Kappa]2^2( \[Omega]^2-I \[Omega]);
\[Zeta]2=Sqrt[arg\[Zeta]2];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I \[Omega])+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I \[Omega])+\[Zeta]2;
B2= -( \[Omega]^2-I \[Omega])(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
A=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   ;
If[Re[A+B1 V1+B2 V2]<-100,0,
E^(A+B1 V1+B2 V2)]
]


FourierPayOff[\[Omega]_,K_,\[Alpha]_,a_]:=(a K (K/\[Alpha])^((I \[Omega])/a))/(\[Omega]^2-I a \[Omega])


LNHestonCallIntegrand[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,S0_,K_,\[Alpha]_,a_,T_,\[Omega]_]:=Re[E^(-I \[Omega]  Log[S0]) LNHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Omega],T]FourierPayOff[\[Omega],K,\[Alpha],a]]


SuperHestonVanillaOptionQ[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,S0_,K_,\[Alpha]_,a_,T_]:=S0-1/\[Pi]Module[{\[Omega]},NIntegrate[LNHestonCallIntegrand[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,S0,K,\[Alpha],a,T,\[Omega]+I/2],
{\[Omega],0,Infinity},MaxRecursion->12]]


SuperHestonVanillaOption[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,S0_,K_,\[Alpha]_,a_,T_]:=S0-1/\[Pi]Module[{\[Omega]},AdaptativeIntegrate[Function[\[Omega],LNHestonCallIntegrand[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,S0,K,\[Alpha],a,T,\[Omega]+I/2]],LegendreCoeffs[60],LegendreCoeffs[8],30,5,10^(-9),30]][[2]]


SuperHestonVanillaOption2[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,S0_,K_,\[Alpha]_,a_,T_]:=S0-1/\[Pi]Module[{\[Omega]},CoeffBasedIntegrate[Function[\[Omega],LNHestonCallIntegrand[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,S0,K,\[Alpha],a,T,\[Omega]+I/2]],LegendreCoeffs[60,0,30]]]


BiSuperHestonFondamentalTransform[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,Z1_,Z2_,\[Alpha]2_,\[Beta]2_,\[Tau]_]:=
Module[{\[Zeta]1,\[Psi]p1 ,\[Psi]m1,A1,arg\[Zeta]1,\[Zeta]2,\[Psi]p2 ,\[Psi]m2,A2,arg\[Zeta]2,\[Zeta]3,\[Psi]p3 ,\[Psi]m3,A3,arg\[Zeta]3,c},
arg\[Zeta]1=(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1);
\[Zeta]1=Sqrt[arg\[Zeta]1];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
arg\[Zeta]2=(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2);
\[Zeta]2=Sqrt[arg\[Zeta]2];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
arg\[Zeta]3=(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2);
\[Zeta]3=Sqrt[arg\[Zeta]3];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
If[Re[c+A1 V1+A2 V2+A3 V3]<-100,0,
E^(c+A1 V1+A2 V2+A3 V3)]
]


BiSuperHestonFondamentalTransformCC=Compile[{{\[Rho]1,_Real},{\[Lambda]v1,_Real},{\[Theta]v1,_Real},{\[Kappa]1,_Real},{V1,_Real},{\[Rho]2,_Real},{\[Lambda]v2,_Real},{\[Theta]v2,_Real},{\[Kappa]2,_Real},{V2,_Real},{\[Rho]3,_Real},{\[Lambda]v3,_Real},{\[Theta]v3,_Real},{\[Kappa]3,_Real},{V3,_Real},{Z1,_Complex},{Z2,_Complex},{\[Tau],_Real},{\[Alpha]2,_Real},{\[Beta]2,_Real}},
Module[{\[Zeta]1=0.0+0.0 I,\[Psi]p1=0.0+0.0 I ,\[Psi]m1=0.0+0.0 I,A1=0.0+0.0 I,arg\[Zeta]1=0.0+0.0 I,
\[Zeta]2=0.0+0.0 I,\[Psi]p2=0.0+0.0 I ,\[Psi]m2=0.0+0.0 I,A2=0.0+0.0 I,arg\[Zeta]2=0.0+0.0 I,
\[Zeta]3=0.0+0.0 I,\[Psi]p3=0.0+0.0 I ,\[Psi]m3=0.0+0.0 I,A3=0.0+0.0 I,arg\[Zeta]3=0.0+0.0 I,c=0.0+0.0 I},
arg\[Zeta]1=(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1);
\[Zeta]1=Sqrt[arg\[Zeta]1];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
arg\[Zeta]2=(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2);
\[Zeta]2=Sqrt[arg\[Zeta]2];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
arg\[Zeta]3=(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2);
\[Zeta]3=Sqrt[arg\[Zeta]3];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
If[Re[c+A1 V1+A2 V2+A3 V3]<-100,0,
E^(c+A1 V1+A2 V2+A3 V3)]
]];


BiSuperHestonFondamentalTransformReverseCC=Compile[{{\[Rho]3,_Real},{\[Lambda]v3,_Real},{\[Theta]v3,_Real},{\[Kappa]3,_Real},{V3,_Real},{\[Rho]2,_Real},{\[Lambda]v2,_Real},{\[Theta]v2,_Real},{\[Kappa]2,_Real},{V2,_Real},{\[Rho]1,_Real},{\[Lambda]v1,_Real},{\[Theta]v1,_Real},{\[Kappa]1,_Real},{V1,_Real},{Z1,_Complex},{Z2,_Complex},{\[Tau],_Real},{\[Beta]2,_Real},{\[Alpha]2,_Real}},
Module[{\[Zeta]1=0.0+0.0 I,\[Psi]p1=0.0+0.0 I ,\[Psi]m1=0.0+0.0 I,A1=0.0+0.0 I,arg\[Zeta]1=0.0+0.0 I,
\[Zeta]2=0.0+0.0 I,\[Psi]p2=0.0+0.0 I ,\[Psi]m2=0.0+0.0 I,A2=0.0+0.0 I,arg\[Zeta]2=0.0+0.0 I,
\[Zeta]3=0.0+0.0 I,\[Psi]p3=0.0+0.0 I ,\[Psi]m3=0.0+0.0 I,A3=0.0+0.0 I,arg\[Zeta]3=0.0+0.0 I,c=0.0+0.0 I},
arg\[Zeta]1=(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1);
\[Zeta]1=Sqrt[arg\[Zeta]1];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
arg\[Zeta]2=(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2);
\[Zeta]2=Sqrt[arg\[Zeta]2];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
arg\[Zeta]3=(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2);
\[Zeta]3=Sqrt[arg\[Zeta]3];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
If[Re[c+A1 V1+A2 V2+A3 V3]<-100,0,
E^(c+A1 V1+A2 V2+A3 V3)]
]];


BiSuperHestonFondamentalTransformReverse[\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,Z1_,Z2_,\[Beta]2_,\[Alpha]2_,\[Tau]_]:=
Module[{\[Zeta]1,\[Psi]p1 ,\[Psi]m1,A1,arg\[Zeta]1,\[Zeta]2,\[Psi]p2 ,\[Psi]m2,A2,arg\[Zeta]2,\[Zeta]3,\[Psi]p3 ,\[Psi]m3,A3,arg\[Zeta]3,c},
arg\[Zeta]1=(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1);
\[Zeta]1=Sqrt[arg\[Zeta]1];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
arg\[Zeta]2=(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2);
\[Zeta]2=Sqrt[arg\[Zeta]2];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
arg\[Zeta]3=(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2);
\[Zeta]3=Sqrt[arg\[Zeta]3];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
If[Re[c+A1 V1+A2 V2+A3 V3]<-100,0,
E^(c+A1 V1+A2 V2+A3 V3)]
]


SmileSymetrizedBiSuperHestonVanillaIntegrand[Y_,\[Alpha]1_,\[Beta]1_,a_,b_,KList_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]m2_,\[Beta]m2_,
\[Lambda]1_,\[Lambda]2_,\[Omega]1_,\[Omega]2_]:=Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[If[KList[[1]]>=0,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);

propagatorDroit=BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2,\[Tau]];SympropagatorDroit=BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1,k2,\[Tau]];
propagatorGauche=BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2A,\[Tau]];SympropagatorGauche=BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1A,k2A,\[Tau]];
Table[If[KList[[i]]>0,\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1A,k2A,KList[[i]],\[Alpha]1,\[Beta]1,a,b],
\[Alpha] propagatorDroit VanillaPayOffFourierDroite[k1,k2,\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroite[Sk1,k2,\[Alpha]1,\[Beta]1,a,b]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGauche[k1,k2A,\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGauche[Sk1,k2A,\[Alpha]1,\[Beta]1,a,b]],{i,1,Length[KList]}],
\[Alpha]2=E^(-I x2 k1-I x1 k2);\[Alpha]A2=E^(-I x2 k1-I x1 k2A);Sym\[Alpha]2=E^(-I x2 Sk1-I x1 k2);Sym\[Alpha]A2=E^(-I x2 Sk1A-I x1 k2A);
propagatorDroit2=BiSuperHestonFondamentalTransformReverse[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2,\[Tau]];SympropagatorDroit2=BiSuperHestonFondamentalTransformReverse[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1,k2,\[Tau]];
propagatorGauche2=BiSuperHestonFondamentalTransformReverse[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2A,\[Tau]];SympropagatorGauche2=BiSuperHestonFondamentalTransformReverse[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1A,k2A,\[Tau]];Table[(\[Alpha]2 (propagatorDroit2 (VanillaPayOffFourierDroite[k1,k2,-KList[[i]],\[Alpha]1,\[Beta]1,a,b]))+Sym\[Alpha]2 (SympropagatorDroit2 (VanillaPayOffFourierDroite[Sk1,k2,-KList[[i]],\[Alpha]1,\[Beta]1,a,b]))) +
(\[Alpha]A2 propagatorGauche2 ( VanillaPayOffFourierGauche[k1,k2A,-KList[[i]],\[Alpha]1,\[Beta]1,a,b])+Sym\[Alpha]A2 SympropagatorGauche2 (VanillaPayOffFourierGauche[Sk1A,k2A,-KList[[i]],\[Alpha]1,\[Beta]1,a,b])),{i,1,Length[KList]}]
]]]


SmileSymetrizedBiSuperHestonVanillaIntegrandCC=Compile[{{Y,_Real,1},{\[Alpha]1,_Real},{\[Beta]1,_Real},{a,_Real},{b,_Real},{KList,_Real,1},{\[Tau],_Real},
{\[Rho]1,_Real},{\[Lambda]v1,_Real},{\[Theta]v1,_Real},{\[Kappa]1,_Real},{V1,_Real},{\[Rho]2,_Real},{\[Lambda]v2,_Real},{\[Theta]v2,_Real},{\[Kappa]2,_Real},{V2,_Real},{\[Rho]3,_Real},{\[Lambda]v3,_Real},{\[Theta]v3,_Real},{\[Kappa]3,_Real},{V3,_Real},{\[Alpha]m2,_Real},{\[Beta]m2,_Real},
{\[Lambda]1,_Real},{\[Lambda]2,_Real},{\[Omega]1,_Complex},{\[Omega]2,_Complex}},Module[{x1=Y[[1]],x2=Y[[2]],k1=(\[Omega]1+I \[Lambda]1),Sk1=(-\[Omega]1+I \[Lambda]1),k2= (\[Omega]2+I \[Lambda]2),Sk2= (-\[Omega]2+I \[Lambda]2),Sk1A=(-\[Omega]1+I \[Lambda]1),k1A=(\[Omega]1-I \[Lambda]1),k2A=(\[Omega]2-I \[Lambda]2),\[Alpha],\[Alpha]A,Sym\[Alpha],Sym\[Alpha]A,\[Alpha]2,\[Alpha]A2,Sym\[Alpha]2,Sym\[Alpha]A2,propagatorDroit,SympropagatorDroit,propagatorGauche,SympropagatorGauche,propagatorDroit2,SympropagatorDroit2,propagatorGauche2,SympropagatorGauche2},
Re[If[KList[[1]]>=0,
\[Alpha]=E^(-I x1 k1-I x2 k2);\[Alpha]A=E^(-I x1 k1-I x2 k2A);Sym\[Alpha]=E^(-I x1 Sk1-I x2 k2);Sym\[Alpha]A=E^(-I x1 Sk1A-I x2 k2A);

propagatorDroit=BiSuperHestonFondamentalTransformCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2,\[Tau]];SympropagatorDroit=BiSuperHestonFondamentalTransformCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1,k2,\[Tau]];
propagatorGauche=BiSuperHestonFondamentalTransformCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2A,\[Tau]];SympropagatorGauche=BiSuperHestonFondamentalTransformCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1A,k2A,\[Tau]];
Table[If[KList[[i]]>0,\[Alpha] propagatorDroit VanillaPayOffFourierDroiteCC[k1,k2,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroiteCC[Sk1,k2,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGaucheCC[k1,k2A,KList[[i]],\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGaucheCC[Sk1A,k2A,KList[[i]],\[Alpha]1,\[Beta]1,a,b],
\[Alpha] propagatorDroit VanillaPayOffFourierDroiteCC0[k1,k2,\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha] SympropagatorDroit VanillaPayOffFourierDroiteCC0[Sk1,k2,\[Alpha]1,\[Beta]1,a,b]+
\[Alpha]A propagatorGauche VanillaPayOffFourierGaucheCC0[k1,k2A,\[Alpha]1,\[Beta]1,a,b]+
Sym\[Alpha]A SympropagatorGauche VanillaPayOffFourierGaucheCC0[Sk1,k2A,\[Alpha]1,\[Beta]1,a,b]],{i,1,Length[KList]}],

\[Alpha]2=E^(-I x2 k1-I x1 k2);\[Alpha]A2=E^(-I x2 k1-I x1 k2A);Sym\[Alpha]2=E^(-I x2 Sk1-I x1 k2);Sym\[Alpha]A2=E^(-I x2 Sk1A-I x1 k2A);
propagatorDroit2=BiSuperHestonFondamentalTransformReverseCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2,\[Tau]];SympropagatorDroit2=BiSuperHestonFondamentalTransformReverseCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1,k2,\[Tau]];
propagatorGauche2=BiSuperHestonFondamentalTransformReverseCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,k1,k2A,\[Tau]];SympropagatorGauche2=BiSuperHestonFondamentalTransformReverseCC[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]m2,\[Beta]m2,Sk1A,k2A,\[Tau]];Table[(\[Alpha]2 (propagatorDroit2 (VanillaPayOffFourierDroiteCC[k1,k2,-KList[[i]],\[Alpha]1,\[Beta]1,a,b]))+Sym\[Alpha]2 (SympropagatorDroit2 (VanillaPayOffFourierDroiteCC[Sk1,k2,-KList[[i]],\[Alpha]1,\[Beta]1,a,b]))) +
(\[Alpha]A2 propagatorGauche2 ( VanillaPayOffFourierGaucheCC[k1,k2A,-KList[[i]],\[Alpha]1,\[Beta]1,a,b])+Sym\[Alpha]A2 SympropagatorGauche2 (VanillaPayOffFourierGaucheCC[Sk1A,k2A,-KList[[i]],\[Alpha]1,\[Beta]1,a,b])),{i,1,Length[KList]}]
]]]];


SmileBiSuperHestonVanillaAux[S_,\[Alpha]1_,\[Beta]1_,a_,b_,KList_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,
\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_,startmonitortime_,plafondexplosion_,initialTailFlag_,InitialTailPosition_,InitialTailPosition2_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_,kmax_,StartControl_,IncrementFactor_},printflag_]:=
2/(2\[Pi])^2Module[{as,res,res2,Y={Log[S[[1]]],Log[S[[2]]]}},
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",S // MatrixForm,
" Process V1=",{{"V1",V1},{"\[Lambda]v1",\[Lambda]v1},{"\[Theta]v1",\[Theta]v1},{"\[Kappa]1",\[Kappa]1},{"\[Rho]1",\[Rho]1}} //MatrixForm,
" Process V2=",{{"V2",V2},{"\[Lambda]v2",\[Lambda]v2},{"\[Theta]v2",\[Theta]v2},{"\[Kappa]2",\[Kappa]2},{"\[Rho]2",\[Rho]2}} //MatrixForm,
" Process V3=",{{"V3",V3},{"\[Lambda]v2",\[Lambda]v3},{"\[Theta]v3",\[Theta]v3},{"\[Kappa]3",\[Kappa]3},{"\[Rho]3",\[Rho]3}} //MatrixForm,
" T=",\[Tau]];
Print["Inner Integration",{{"LegendreNbMain",Length[LegendreCoef1]},{"LegendreNbIncrement",Length[LegendreCoef1n]},{"IncrementNbMax",imax},{"InitialTailFlag",initialTailFlag},{"InitialTailLegendreNb",Length[LegendreCoef2]},{"PeriodMain",period1},{"PeriodnIncrement",period1n},{"StoppingLevel",\[Epsilon]1},
{"AbcisseMaxValue",kmax},{"InitialTailUpperLimit",InitialTailPosition},
{"ExplosionMonitoringStartAbcisse",StartControl},{"ExplosionMonitoringMaxLevel",IncrementFactor},
{"lambda1",\[Lambda]1},{"lambda2",\[Lambda]2}} // MatrixForm,
"Outer Integration",{{"LegendreNbMain",Length[LegendreCoef2]},{"LegendreNbIncrement",Length[LegendreCoef1n]},{"IncrementNbMax",imax},{"InitialTailFlag",initialTailFlag},{"InitialTailLegendreNb",Length[LegendreCoef1]},{"PeriodMain",period2},{"PeriodnIncrement",period2n},{"StoppingLevel",\[Epsilon]2},
{"AbcisseMaxValue",kmax},{"InitialTailUpperLimit",InitialTailPosition},
{"GrowingControlStartAbcisse",startmonitortime},{"GrowingControlMaxFactor",plafondexplosion}} // MatrixForm]];
If[printflag==2 || MemberQ[printflag,2]  ,Print["BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,Z1,Z2,\[Tau]]=",BiSuperHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,0.1,0.1,\[Tau]]];
Print["integrand(0.1,0.1)=",SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,0.1,0.1]]];
If[printflag==4|| MemberQ[printflag,4] ,Print[Table[Plot[SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,{KList[[1]]},\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2][[1]],{\[Omega]2,0 ,2period1},PlotPoints->50,PlotRange->All,PlotLabel->"1st Inverse Fourier: K ="<>ToString[KList[[1]]]<>" \[Omega]1="<>ToString[\[Omega]1]],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==5|| MemberQ[printflag,5] ,Print[Table[Plot[SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,{KList[[1]]},\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2][[1]],{\[Omega]2,0 ,2period1},PlotPoints->50,PlotLabel->"1st Inverse Fourier: K ="<>ToString[KList[[1]]]<>" \[Omega]1="<>ToString[\[Omega]1],PlotRange->All],{\[Omega]1,{0,0.2,2}}]]];
If[printflag==6|| MemberQ[printflag,6] ,Print[ListPlot[Table[{\[Omega]2,VectorAdaptativeIntegrateExplosionSafe[Function[\[Omega]1,SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,{KList[[1]]},\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2][[1]]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,1,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition][[2,1]]},{\[Omega]2,0,2period2,period2/30}],Joined->True,PlotLabel->"2nd Inverse Fourier:",PlotRange->All]]];
If[printflag==7|| MemberQ[printflag,7] ,Print["integrand(0.1,0.1)=",SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,0.1,0.1]]];
If[printflag==7|| MemberQ[printflag,7] ,Print["code integ 2 : {i,exploded<1,Abs[increment[[1]]]>\[Epsilon],(i<imax)}"];
Print["code integ 1 : {i,exploded<1,Abs[increment[[1]]]>\[Epsilon],(i<imax)}"]];
res=VectorAdaptativeIntegrateUnprotected[Function[\[Omega]2,as=VectorAdaptativeIntegrateExplosionSafe[Function[\[Omega]1,SmileSymetrizedBiSuperHestonVanillaIntegrandCC[Y,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Lambda]1,\[Lambda]2,\[Omega]1,\[Omega]2]],LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,Length[KList],startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition];If[printflag==7|| MemberQ[printflag,7],Print["\[Omega]2=",\[Omega]2," Integ_2=",as]];as[[2]]],LegendreCoef2,LegendreCoef1n,period2,period2n,\[Epsilon]2,imax,Length[KList],printflag,initialTailFlag,InitialTailPosition2,kmax,StartControl,IncrementFactor];
If[printflag==7|| MemberQ[printflag,7],Print["Integ_1=",res]];
res[[2]]]


SmileBiSuperHestonVanillaPositiveK[S_,\[Alpha]1_,\[Beta]1_,a_,b_,KList_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,
\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_,startmonitortime_,plafondexplosion_,initialTailFlag_,InitialTailPosition_,InitialTailPosition2_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_,kmax_,StartControl_,IncrementFactor_},printflag_]:=SmileBiSuperHestonVanillaAux[S,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,
\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},printflag]


SmileBiSuperHestonVanillaNegativeK[S_,\[Alpha]1_,\[Beta]1_,a_,b_,KList_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,
\[Lambda]1_,\[Lambda]2_,{LegendreCoef1_,LegendreCoef1n_,period1_,period1n_,\[Epsilon]1_,imax_,startmonitortime_,plafondexplosion_,initialTailFlag_,InitialTailPosition_,InitialTailPosition2_},{LegendreCoef2_,period2_,period2n_,\[Epsilon]2_,kmax_,StartControl_,IncrementFactor_},printflag_]:=SmileBiSuperHestonVanillaAux[S,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,
\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},printflag]+S[[1]]-S[[2]]-KList


SmileBiSuperHestonVanillaSpreadotion[S_,\[Alpha]1_,\[Beta]1_,a_,b_,KList1_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,
printflag_]:=Module[{KList,LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,\[Lambda]1,\[Lambda]2,KListPositive,KListNegative,KPositivePrices={},KNegativePrices={},prices,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2,kmax,StartControl,IncrementFactor,\[CapitalSigma]inf},

If[Length[KList1]==0,KList={KList1},KList=KList1];
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},imax,\[Lambda]1,\[Lambda]2}=BiSuperHestonVanillaOptimalParameters[S,\[Alpha]1,\[Beta]1,a,b,KList[[1]],\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,
"VanillaSpreadoption",printflag];
KListPositive=Select[KList,#>=0&];KListNegative=Select[KList,#<0&];
If[Length[KListPositive]>0,KPositivePrices=SmileBiSuperHestonVanillaPositiveK[S,\[Alpha]1,\[Beta]1,a,b,KListPositive,\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,
\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},printflag]];
If[(printflag==1)||(MemberQ[printflag ,1]),Print["Fin partie positive"]];
If[Length[KListNegative]>0,KNegativePrices=SmileBiSuperHestonVanillaNegativeK[S,\[Alpha]1,\[Beta]1,a,b,KListNegative,\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,
\[Lambda]1,\[Lambda]2,{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,imax,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},If[MemberQ[printflag,1],Drop[printflag,1],printflag]]];
prices=Join[KNegativePrices,KPositivePrices];
Table[Max[\[Alpha]1 S[[1]]^a-\[Beta]1 S[[2]]^b-KList1[[i]],0,prices[[i]]],{i,1,Length[KList1]}]
]


BiSuperHestonVanillaOptimalParameters[S_,\[Alpha]1_,\[Beta]1_,a1_,b1_,K_,\[Tau]_,
\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,
type_,printflag_]:=Module[{\[Lambda]1,\[Lambda]2,scope1,scope2,Nb1,LegendreCoef1,Nb1n,LegendreCoef1n,period1,period1n,\[Epsilon]1,Nb2,LegendreCoef2,period2,period2n,\[Epsilon]2,imax,s1=S[[1]],s2=S[[2]],Rmax,smax,smin,forward=S[[1]]-S[[2]],scopeDivisor1=1,scopeDivisor1n=1,scopeDivisor2=1,scopeDivisor2n=1,VolNb,\[CapitalSigma]moyen,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2,kmax,StartControl,IncrementFactor},
If[(type=="VanillaSpreadoption"),
\[Lambda]1=1.1;\[Lambda]2=1.01;imax=10;
period1=10;period1n=5;period2=10;period2n=5.;
Nb1=50;Nb2=50;Nb1n=20;\[Epsilon]1=0.000001;\[Epsilon]2=0.00001;
startmonitortime=2;
plafondexplosion=0.1;
initialTailFlag=1;
InitialTailPosition=0.5;
InitialTailPosition2=2;
kmax=100;
StartControl=20;
IncrementFactor=2;
];
LegendreCoef1=LegendreCoeffs[Nb1];LegendreCoef1n=LegendreCoeffs[Nb1n];
LegendreCoef2=LegendreCoeffs[Nb2];
{{LegendreCoef1,LegendreCoef1n,period1,period1n,\[Epsilon]1,startmonitortime,plafondexplosion,initialTailFlag,InitialTailPosition,InitialTailPosition2},{LegendreCoef2,period2,period2n,\[Epsilon]2,kmax,StartControl,IncrementFactor},imax,\[Lambda]1,\[Lambda]2}]



PackagedSmileBiSuperHestonUnderlyingOption1[S1_,S2_,\[Alpha]_,a_,KList_,T_,
VolS1_,VolS2_,Correl12_,\[Rho]S1_,\[Rho]S2_,\[Rho]S3_,\[Kappa]S1_,\[Kappa]S2_,\[Kappa]S3_,\[Lambda]1_,\[Lambda]2_,\[Lambda]3_,LTVarianceFactor1_,LTVarianceFactor2_,LTVarianceFactor3_,
printflag_]:=
Module[{S,\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3},
V2=Sqrt[VolS1] Sqrt[VolS2] Correl12;V1=VolS1-V2;V3=VolS2-V2;
 \[Kappa]1=\[Kappa]S1;\[Kappa]2=\[Kappa]S2;\[Kappa]3=\[Kappa]S3;
\[Rho]1=\[Rho]S1;\[Rho]2=\[Rho]S2;\[Rho]3=\[Rho]S3;
\[Theta]v1=V1 LTVarianceFactor1;\[Theta]v2=V2 LTVarianceFactor2;\[Theta]v3=V3 LTVarianceFactor3;
\[Lambda]v1=\[Lambda]1;\[Lambda]v2=\[Lambda]2;\[Lambda]v3=\[Lambda]3;
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",{S1,S2} // MatrixForm,
" Process V1=",{{"V1",V1},{"\[Lambda]v1",\[Lambda]v1},{"\[Theta]v1",\[Theta]v1},{"\[Kappa]1",\[Kappa]1},{"\[Rho]1",\[Rho]1}} //MatrixForm,
" Process V2=",{{"V2",V2},{"\[Lambda]v2",\[Lambda]v2},{"\[Theta]v2",\[Theta]v2},{"\[Kappa]2",\[Kappa]2},{"\[Rho]2",\[Rho]2}} //MatrixForm,
" Process V3=",{{"V3",V3},{"\[Lambda]v2",\[Lambda]v3},{"\[Theta]v3",\[Theta]v3},{"\[Kappa]3",\[Kappa]3},{"\[Rho]3",\[Rho]3}} //MatrixForm,
" T=",T]];
Table[SuperHestonVanillaOption[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,S1,KList[[i]],\[Alpha],a,T],{i,1,Length[KList]}]]


PackagedSmileBiSuperHestonUnderlyingOption2[S1_,S2_,\[Alpha]_,a_,KList_,T_,
VolS1_,VolS2_,Correl12_,\[Rho]S1_,\[Rho]S2_,\[Rho]S3_,\[Kappa]S1_,\[Kappa]S2_,\[Kappa]S3_,\[Lambda]1_,\[Lambda]2_,\[Lambda]3_,LTVarianceFactor1_,LTVarianceFactor2_,LTVarianceFactor3_,
printflag_]:=
Module[{S,\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3},
V2=Sqrt[VolS1] Sqrt[VolS2] Correl12;V1=VolS1-V2;V3=VolS2-V2;
\[Kappa]1=\[Kappa]S1;\[Kappa]2=\[Kappa]S2;\[Kappa]3=\[Kappa]S3;
\[Rho]1=\[Rho]S1;\[Rho]2=\[Rho]S2;\[Rho]3=\[Rho]S3;
\[Theta]v1=V1 LTVarianceFactor1;\[Theta]v2=V2 LTVarianceFactor2;\[Theta]v3=V3 LTVarianceFactor3;
\[Lambda]v1=\[Lambda]1;\[Lambda]v2=\[Lambda]2;\[Lambda]v3=\[Lambda]3;
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",{S1,S2} // MatrixForm,
" Process V1=",{{"V1",V1},{"\[Lambda]v1",\[Lambda]v1},{"\[Theta]v1",\[Theta]v1},{"\[Kappa]1",\[Kappa]1},{"\[Rho]1",\[Rho]1}} //MatrixForm,
" Process V2=",{{"V2",V2},{"\[Lambda]v2",\[Lambda]v2},{"\[Theta]v2",\[Theta]v2},{"\[Kappa]2",\[Kappa]2},{"\[Rho]2",\[Rho]2}} //MatrixForm,
" Process V3=",{{"V3",V3},{"\[Lambda]v2",\[Lambda]v3},{"\[Theta]v3",\[Theta]v3},{"\[Kappa]3",\[Kappa]3},{"\[Rho]3",\[Rho]3}} //MatrixForm,
" T=",T]];
Table[SuperHestonVanillaOption[\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,S2,KList[[i]],\[Alpha],a,T],{i,1,Length[KList]}]]


PackagedSmileFourierBiSuperHestonVanillaSpreadoption[S1_,S2_,\[Alpha]1_,\[Beta]1_,a_,b_,KList_,\[Tau]_,
VolS1_,VolS2_,Correl12_,\[Rho]S1_,\[Rho]S2_,\[Rho]S3_,\[Kappa]S1_,\[Kappa]S2_,\[Kappa]S3_,\[Lambda]1_,\[Lambda]2_,\[Lambda]3_,LTVarianceFactor1_,LTVarianceFactor2_,LTVarianceFactor3_,
printflag_]:=
Module[{S,\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3},
S={S1,S2};
V2=Sqrt[VolS1] Sqrt[VolS2] Correl12;
V1=VolS1-V2;
V3=VolS2-V2;
 \[Kappa]1=\[Kappa]S1;\[Kappa]2=\[Kappa]S2;\[Kappa]3=\[Kappa]S3;
\[Rho]1=\[Rho]S1;\[Rho]2=\[Rho]S2;\[Rho]3=\[Rho]S3;
\[Theta]v1=V1 LTVarianceFactor1;
\[Theta]v2=V2 LTVarianceFactor2;
\[Theta]v3=V3 LTVarianceFactor3;
\[Lambda]v1=\[Lambda]1;\[Lambda]v2=\[Lambda]2;\[Lambda]v3=\[Lambda]3;
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",{S1,S2} // MatrixForm,
" Process V1=",{{"V1",V1},{"\[Lambda]v1",\[Lambda]v1},{"\[Theta]v1",\[Theta]v1},{"\[Kappa]1",\[Kappa]1},{"\[Rho]1",\[Rho]1}} //MatrixForm,
" Process V2=",{{"V2",V2},{"\[Lambda]v2",\[Lambda]v2},{"\[Theta]v2",\[Theta]v2},{"\[Kappa]2",\[Kappa]2},{"\[Rho]2",\[Rho]2}} //MatrixForm,
" Process V3=",{{"V3",V3},{"\[Lambda]v2",\[Lambda]v3},{"\[Theta]v3",\[Theta]v3},{"\[Kappa]3",\[Kappa]3},{"\[Rho]3",\[Rho]3}} //MatrixForm,
" T=",\[Tau]]];
If[printflag==9 || MemberQ[printflag,9]  ,
Print[Plot3D[SmileSymetrizedBiSuperHestonVanillaIntegrand[{S1,S2},\[Alpha]1,\[Beta]1,a,b,{0},\[Tau],\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,1.1,1.01,Z1,Z2][[1]],{Z1,-1,1},{Z2,-5,5},PlotRange->All]]];
SmileBiSuperHestonVanillaSpreadotion[S,\[Alpha]1,\[Beta]1,a,b,KList,\[Tau],
\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,
printflag]]


LogNormalHestonFondamentalTransform[\[Rho]_,\[Lambda]v_,\[Theta]v_,\[Kappa]_,V_,\[Omega]_,\[Tau]_]:=Module[{\[Zeta],\[Psi]p ,\[Psi]m,A,B,arg\[Zeta]},
\[Zeta]=Sqrt[(\[Lambda]v+\[Rho] \[Kappa] I \[Omega])^2+\[Kappa]^2( \[Omega]^2)];
\[Psi]p =-(\[Lambda]v+\[Rho] \[Kappa]  I \[Omega])+\[Zeta];
\[Psi]m =(\[Lambda]v+\[Rho] \[Kappa]  I \[Omega])+\[Zeta];
A=-( \[Theta]v \[Lambda]v (\[Tau] \[Psi]p+2 Log[(\[Psi]m+E^(-\[Zeta] \[Tau]) \[Psi]p)/(2\[Zeta])])/ (\[Kappa]^2)   );
B= -( \[Omega]^2)(1-E^(-\[Zeta]  \[Tau]))/(\[Psi]m+\[Psi]p E^(-\[Zeta]  \[Tau]));
A+B V]


D2=D[LogNormalHestonFondamentalTransform[\[Rho],\[Lambda]v,\[Theta]v,\[Kappa],V,\[Omega],\[Tau]],{\[Omega],2}];
D2LogNormalHestonFondamentalTransform=Function[{\[Rho],\[Lambda]v,\[Theta]v,\[Kappa],V,\[Tau]},Evaluate[1/I^2D2/. \[Omega]->0]];


D2LogNormalHestonFondamentalTransform=Function[{\[Rho],\[Lambda]v,\[Theta]v,\[Kappa],V,\[Tau]},Evaluate[Simplify[D2LogNormalHestonFondamentalTransform[\[Rho],\[Lambda]v,\[Theta]v,\[Kappa],V,\[Tau]]]]];


BiSuperLogNormalHestonFondamentalTransform[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,Z1_,Z2_,\[Tau]_]:=
Module[{\[Zeta]1,\[Psi]p1 ,\[Psi]m1,A1,\[Zeta]2,\[Psi]p2 ,\[Psi]m2,A2,\[Zeta]3,\[Psi]p3 ,\[Psi]m3,A3,c},
\[Zeta]1=Sqrt[(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1)];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
\[Zeta]2=Sqrt[(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
\[Zeta]3=Sqrt[(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2)];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
E^(c+A1 V1+A2 V2+A3 V3)]


LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,Z1_,Z2_,\[Tau]_]:=
Module[{\[Zeta]1,\[Psi]p1 ,\[Psi]m1,A1,\[Zeta]2,\[Psi]p2 ,\[Psi]m2,A2,\[Zeta]3,\[Psi]p3 ,\[Psi]m3,A3,c},
\[Zeta]1=Sqrt[(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)^2+\[Kappa]1^2( Z1^2-I Z1)];
\[Psi]p1 =-(\[Lambda]v1+\[Rho]1 \[Kappa]1 I Z1)+\[Zeta]1;
\[Psi]m1 =(\[Lambda]v1+\[Rho]1 \[Kappa]1  I Z1)+\[Zeta]1;
A1= -( Z1^2-I Z1)(1-E^(-\[Zeta]1  \[Tau]))/(\[Psi]m1+\[Psi]p1 E^(-\[Zeta]1  \[Tau]));
\[Zeta]2=Sqrt[(\[Lambda]v2+\[Rho]2 \[Kappa]2 I (Z1 \[Alpha]2+Z2 \[Beta]2))^2+\[Kappa]2^2( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)];
\[Psi]p2 =-(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
\[Psi]m2 =(\[Lambda]v2+\[Rho]2 \[Kappa]2  I (Z1 \[Alpha]2+Z2 \[Beta]2))+\[Zeta]2;
A2= -( Z1 (-I+Z1) \[Alpha]2^2+2 Z1 Z2 \[Alpha]2 \[Beta]2+Z2 (-I+Z2) \[Beta]2^2)(1-E^(-\[Zeta]2  \[Tau]))/(\[Psi]m2+\[Psi]p2 E^(-\[Zeta]2  \[Tau]));
\[Zeta]3=Sqrt[(\[Lambda]v3+\[Rho]3 \[Kappa]3 I Z2)^2+\[Kappa]3^2( Z2^2-I Z2)];
\[Psi]p3 =-(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
\[Psi]m3 =(\[Lambda]v3+\[Rho]3 \[Kappa]3  I Z2)+\[Zeta]3;
A3= -( Z2^2-I Z2)(1-E^(-\[Zeta]3  \[Tau]))/(\[Psi]m3+\[Psi]p3 E^(-\[Zeta]3  \[Tau]));

c=-( \[Theta]v1 \[Lambda]v1 (\[Tau] \[Psi]p1+2 Log[(\[Psi]m1+E^(-\[Zeta]1 \[Tau]) \[Psi]p1)/(2\[Zeta]1)])/ (\[Kappa]1^2)   )- \[Theta]v2 \[Lambda]v2 (\[Tau] \[Psi]p2+2 Log[(\[Psi]m2+E^(-\[Zeta]2 \[Tau]) \[Psi]p2)/(2\[Zeta]2)])/ (\[Kappa]2^2)   - \[Theta]v3 \[Lambda]v3 (\[Tau] \[Psi]p3+2 Log[(\[Psi]m3+E^(-\[Zeta]3 \[Tau]) \[Psi]p3)/(2\[Zeta]3)])/ (\[Kappa]3^2)   ;
c+A1 V1+A2 V2+A3 V3]


D1X=D[LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,Z1,Z2,\[Tau]],Z1];
D1XBiSuperLogNormalHestonFondamentalTransform=Function[{\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]},Evaluate[1/ID1X /.{Z1->0,Z2->0}]];


D1Y=D[LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,Z1,Z2,\[Tau]],Z2];
D1YBiSuperLogNormalHestonFondamentalTransform=Function[{\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]},Evaluate[1/ID1Y/.{Z1->0,Z2->0}]];


D2XX=D[LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,Z1,Z2,\[Tau]],{Z1,2}];
D2XXBiSuperLogNormalHestonFondamentalTransform=Function[{\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]},Evaluate[1/I^2D2XX/.{Z1->0,Z2->0}]];


D2YY=D[LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,Z1,Z2,\[Tau]],{Z2,2}];
D2YYBiSuperLogNormalHestonFondamentalTransform=Function[{\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]},Evaluate[1/I^2D2YY/.{Z1->0,Z2->0}]];


D2XY=D[LogBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,Z1,Z2,\[Tau]],Z1,Z2];
D2XYBiSuperLogNormalHestonFondamentalTransform=Function[{\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]},Evaluate[1/I^2D2XY/.{Z1->0,Z2->0}]];


SmileBiSuperHestonVanillaSpreadOption[S1_,S2_, \[Rho]1_,\[Lambda]v1_,\[Theta]v1_,\[Kappa]1_,V1_,\[Rho]2_,\[Lambda]v2_,\[Theta]v2_,\[Kappa]2_,V2_,\[Rho]3_,\[Lambda]v3_,\[Theta]v3_,\[Kappa]3_,V3_,\[Alpha]2_,\[Beta]2_,SpreadStrikes_,\[Tau]_,printflag_]:=Module[{Z1,Z2,VarExpX,VarExpY,VarRealSpead,\[Rho]projet\[EAcute],\[Nu]projet\[EAcute],
\[Mu]X,\[Mu]Y,\[Mu]XX,\[Mu]YY,\[Mu]XY,\[Mu]XXX,\[Mu]XXY,\[Mu]XYY,\[Mu]YYY,\[Mu]XXXX,\[Mu]XXXY,\[Mu]XXYY,\[Mu]XYYY,\[Mu]YYYY,
\[Mu]1,\[Mu]2,\[Mu]3,\[Mu]4,V0Generateur,\[Kappa]S,\[Rho]S,\[Lambda]S,LTFactorS,TrueIniVarSpread,x,prices,logcorrelT,\[Rho]model,VarVS,CoVarSVS,VS},
{{\[Mu]X,\[Mu]Y},{\[Mu]XX,\[Mu]YY,\[Mu]XY}}=
{{D1XBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]],
D1YBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]]},
{D2XXBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]],
D2YYBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]],
D2XYBiSuperLogNormalHestonFondamentalTransform[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Alpha]2,\[Beta]2,\[Tau]]}};
If[printflag==1 || MemberQ[printflag,1] ,Print["moments=",{{\[Mu]X,\[Mu]Y},{\[Mu]XX,\[Mu]YY,\[Mu]XY}}]];
logcorrelT=\[Mu]XY/Sqrt[\[Mu]XX \[Mu]YY ];
If[printflag==1 || MemberQ[printflag,1] ,Print["logcorrelT=",logcorrelT]];
VarVS=S1^2 V1 (2 S1 (V1+V2 \[Alpha]2^2)-2 S2 V2 \[Alpha]2 \[Beta]2) (2 S1 V1+2 V2 \[Alpha]2 (S1 \[Alpha]2-S2 \[Beta]2)+S1 \[Kappa]1 \[Rho]1)+S1^3 V1 \[Kappa]1 (-2 S2 V2 \[Alpha]2 \[Beta]2 \[Rho]1+S1 (\[Kappa]1+2 (V1+V2 \[Alpha]2^2) \[Rho]1))+V2 (S1 \[Alpha]2-S2 \[Beta]2)^2 \[Kappa]2 ((S1 \[Alpha]2-S2 \[Beta]2)^2 \[Kappa]2+(2 S1^2 \[Alpha]2 (V1+V2 \[Alpha]2^2)-2 S1 S2 V2 \[Alpha]2 \[Beta]2 (\[Alpha]2+\[Beta]2)+2 S2^2 \[Beta]2 (V3+V2 \[Beta]2^2)) \[Rho]2)+V2 (2 S1^2 \[Alpha]2 (V1+V2 \[Alpha]2^2)-2 S1 S2 V2 \[Alpha]2 \[Beta]2 (\[Alpha]2+\[Beta]2)+2 S2^2 \[Beta]2 (V3+V2 \[Beta]2^2)) (-2 S1 S2 \[Alpha]2 \[Beta]2 (V2 (\[Alpha]2+\[Beta]2)+\[Kappa]2 \[Rho]2)+S1^2 \[Alpha]2 (2 V1+\[Alpha]2 (2 V2 \[Alpha]2+\[Kappa]2 \[Rho]2))+S2^2 \[Beta]2 (2 V3+\[Beta]2 (2 V2 \[Beta]2+\[Kappa]2 \[Rho]2)))+S2^3 V3 \[Kappa]3 (-2 S1 V2 \[Alpha]2 \[Beta]2 \[Rho]3+S2 (\[Kappa]3+2 (V3+V2 \[Beta]2^2) \[Rho]3))+2 S2^2 V3 (-S1 V2 \[Alpha]2 \[Beta]2+S2 (V3+V2 \[Beta]2^2)) (-2 S1 V2 \[Alpha]2 \[Beta]2+S2 (2 V3+2 V2 \[Beta]2^2+\[Kappa]3 \[Rho]3));
CoVarSVS=2 S1^2 V1 (S1 (V1+V2 \[Alpha]2^2)-S2 V2 \[Alpha]2 \[Beta]2)-2 S2^2 V3 (-S1 V2 \[Alpha]2 \[Beta]2+S2 (V3+V2 \[Beta]2^2))+V2 (S1 \[Alpha]2-S2 \[Beta]2) (2 S1^2 \[Alpha]2 (V1+V2 \[Alpha]2^2)-2 S1 S2 V2 \[Alpha]2 \[Beta]2 (\[Alpha]2+\[Beta]2)+2 S2^2 \[Beta]2 (V3+V2 \[Beta]2^2))+S1^3 V1 \[Kappa]1 \[Rho]1+V2 (S1 \[Alpha]2-S2 \[Beta]2)^3 \[Kappa]2 \[Rho]2-S2^3 V3 \[Kappa]3 \[Rho]3;
VS=S1^2 V1+S2^2 V3+V2 (S1 \[Alpha]2-S2 \[Beta]2)^2;
\[Rho]projet\[EAcute]=CoVarSVS/VarVS;\[Nu]projet\[EAcute]=Sqrt[VarVS/VS];
VarExpX=LogHestonNormalVariance[\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,Sqrt[\[Alpha]2]V2,S1,\[Tau]];
VarExpY=LogHestonNormalVariance[\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,Sqrt[\[Beta]2]V2,S2,\[Tau]];
VarRealSpead=VarExpX+VarExpY-2logcorrelT Sqrt[VarExpX VarExpY];
If[printflag==1 || MemberQ[printflag,1] ,Print["VarRealSpead (Goal)=",VarRealSpead]];

LTFactorS=1.5;
\[Lambda]S=0.15;

TrueIniVarSpread=(E^(\[Lambda]S \[Tau]) VarRealSpead \[Lambda]S)/(-1+LTFactorS+E^(\[Lambda]S \[Tau]) (1+LTFactorS (-1+\[Lambda]S \[Tau])));
If[printflag==1 || MemberQ[printflag,1] ,Print["TrueIniVarSpread=",TrueIniVarSpread]];

If[printflag==1 || MemberQ[printflag,1] ,Print["TrueIniVarSpread=",TrueIniVarSpread]];
If[printflag==1 || MemberQ[printflag,1] ,Print["Normal Heston Parameters=",{{"S0",S1-S2},{"V0",TrueIniVarSpread},{"\[Theta]",LTFactorS TrueIniVarSpread},{"\[Lambda]v",\[Lambda]S},{"\[Rho]",\[Rho]S},{"\[Nu]",\[Kappa]S}} //MatrixForm]];
prices=HestonNormalCallTrace[\[Rho]S,\[Lambda]S,LTFactorS TrueIniVarSpread,\[Kappa]S,TrueIniVarSpread,S1-S2,SpreadStrikes,\[Tau]];
If[printflag==1 || MemberQ[printflag,1] ,Print["prices=",prices]];
prices
]


PackagedSmileBiSuperHestonVanillaSpreadoptionRapide[S1_,S2_,SpreadStrikes_,\[Tau]_,
VolS1_,VolS2_,Correl12_,\[Rho]S1_,\[Rho]S2_,\[Rho]S3_,\[Kappa]S1_,\[Kappa]S2_,\[Kappa]S3_,\[Lambda]1_,\[Lambda]2_,\[Lambda]3_,LTVarianceFactor1_,LTVarianceFactor2_,LTVarianceFactor3_,
printflag_]:=
Module[{S,\[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3},
S={S1,S2};
V2=Sqrt[VolS1] Sqrt[VolS2] Correl12;
V1=VolS1-V2;
V3=VolS2-V2;
\[Kappa]1=\[Kappa]S1;\[Kappa]2=\[Kappa]S2;\[Kappa]3=\[Kappa]S3;
\[Rho]1=\[Rho]S1;\[Rho]2=\[Rho]S2;\[Rho]3=\[Rho]S3;
\[Theta]v1=V1 LTVarianceFactor1;
\[Theta]v2=V2 LTVarianceFactor2;
\[Theta]v3=V3 LTVarianceFactor3;
\[Lambda]v1=\[Lambda]1;\[Lambda]v2=\[Lambda]2;\[Lambda]v3=\[Lambda]3;
If[printflag==1 || MemberQ[printflag,1]  ,Print[" S=",{S1,S2} // MatrixForm,
" Process V1=",{{"V1",V1},{"\[Lambda]v1",\[Lambda]v1},{"\[Theta]v1",\[Theta]v1},{"\[Kappa]1",\[Kappa]1},{"\[Rho]1",\[Rho]1}} //MatrixForm,
" Process V2=",{{"V2",V2},{"\[Lambda]v2",\[Lambda]v2},{"\[Theta]v2",\[Theta]v2},{"\[Kappa]2",\[Kappa]2},{"\[Rho]2",\[Rho]2}} //MatrixForm,
" Process V3=",{{"V3",V3},{"\[Lambda]v2",\[Lambda]v3},{"\[Theta]v3",\[Theta]v3},{"\[Kappa]3",\[Kappa]3},{"\[Rho]3",\[Rho]3}} //MatrixForm,
" T=",\[Tau]]];
SmileBiSuperHestonVanillaSpreadOption[S1,S2, \[Rho]1,\[Lambda]v1,\[Theta]v1,\[Kappa]1,V1,\[Rho]2,\[Lambda]v2,\[Theta]v2,\[Kappa]2,V2,\[Rho]3,\[Lambda]v3,\[Theta]v3,\[Kappa]3,V3,SpreadStrikes,\[Tau],printflag]]



